Today.Storayboard 구현(4)
42-JMJ/iOS-App-Project pull request #40
Opened 2020-05-01 10:25 UTC by 365kim

### 1. alert함수에서 ListView로 연결되지 않던 문제 해결
- doAction()에 performSegue코드 추가

### 2. Article관련 함수 수정
- setDateAndArticle의 이름을 selectArticle로 수정하고 article을 return하도록 함.
- 반환되는 article은 readQuestion과 btnSaveTouchOn에서 사용

### 3. btnSaveTouchOn함수 작성
- 사용자가 저장 버튼을 누르면 해당 article을 update함
- 성공시 "update sucess" 출력하고 displayView로 전환

### 4. animate 효과 추가
- 질문 -> placeholder -> 목록/저장 버튼 순서로 뜨게 설정
- 회의에서 의견나누고 다시 수정

---

#38 에서 추가한 PR 템플릿 엄청 편리하네요! 
감사합니다.

#### 리뷰어 배정(PR일 기준)
- 홀수일 : 재두 > 미혜 > 준서 > 재두 (재두는 미혜의 코드를 리뷰한다)
- 짝수일 : 재두 < 미혜 < 준서 < 재두 (미혜는 재두의 코드를 리뷰한다)

2020-05-01 12:07 UTC, dev-jko requested changes
OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift 의
32, 33번 줄에서 똑같은 아티클을 사용하는데 db에 두번 접근합니다
한번만 접근하고 변수에 담아서 사용하면 좋을 것 같아요~

2020-05-01 13:28 UTC, 365kim commented
꼼꼼한 코드리뷰 감사드립니다-!
내일 수정해보고 올리겠습니다 :)

그리고 시간되실때 Xcode11에서 화면전환 애니메이션 어떻게 보이는지 확인부탁드릴게요!
(기존대비 바뀌어보이는지 그대로인지?)

2020-05-02 05:19 UTC, nadarm commented
애니메이션 아주 잘 됩니다!

2020-05-02 12:42 UTC, 365kim commented
말씀해주신 부분 수정했습니다!

그 사이에 sqlite로 테이블 만들어주신거 master에 merge되었길래
덕분에 testdb적용되었던것을 sqlitedb로 변경 적용했습니다! (잘되서 씐-나요)

2020-05-02 12:43 UTC, 365kim commented
화면전환 관련해서는
아까 카톡으로 btnSave 눌러서 전환되는 부분은 full screen으로 정상적으로 뜨는데
btnList 눌러서 전환되는 부분은 여전히 문제가 있다고 말씀해주셔서
다시 수정 해봤습니다. 
될지 모르겠지만... 확인 부탁드립니다.!

2020-05-02 13:03 UTC, dev-jko reviewed
OneDayOneAnswer/OneDayOneAnswer/TodayViewController.swift 에서
20번 줄 sqldb를 public으로 설정한 이유가 있나요?

TodayViewController에서 ListViewController로 이동하는 부분 풀스크린으로 잘 나옵니다!

2020-05-02 13:29 UTC, 365kim commented
접근레벨에 대한 큰 고민없이 컴파일 된다고 신난다고 올렸습니다 ㅜㅜ 
역시 예리하십니다... 원래 의도에는 private이 맞는 것 같아 다시 수정했습니다.
1리뷰 1수당 시대가 열리길.... 감사합니다!

드디어 #39 문제가 해결되었군용
확인해주셔서 감사합니다

2020-05-02 13:36 UTC, dev-jko approved these changes
고생 많으셨습니다 승-인

2020-05-02 13:39 UTC, merged