Feature/file
42-JMJ/iOS-App-Project pull request #47
Opened 2020-05-04 12:15 UTC by nadarm

파일 이름을 이용해 이미지를 가져옵니다

# 리뷰어 배정(PR일 기준)
- 홀수일 : 재두 > 미혜 > 준서 > 재두 (재두는 미혜의 코드를 리뷰한다)
- 짝수일 : 재두 < 미혜 < 준서 < 재두 (미혜는 재두의 코드를 리뷰한다)

2020-05-04 12:47 UTC, 365kim commented
와우 벌써 작성하셨다니! 빛보다 빠르십니다  ✨ ✨ ✨ 

getUIImageFromDocDir()
getUIImageFromBundle()
getFileStringFromBundle()
작성하신 세 함수 각각 어느 상황에서 사용되는 건지 간단하게 설명 부탁드려도 될까요?

2020-05-04 13:10 UTC, 365kim requested changes
지금 함수명/변수명도 좋지만 굳이 리뷰를 드리자면
함수명을 getFile __String__ FromBundle에서 getFile __Contents__ FromBundle
그 함수 안에있는 변수명을 __str__ 에서 __fileContents__ 로 바꾸는 건 어떨까요?

2020-05-04 13:10 UTC, 365kim commented on OneDayOneAnswer/OneDayOneAnswer/Utils/FileUtils.swift
> +func getFileStringFromBundle(fileName: String, fileExtension: String) -> String? {
지금 함수명/변수명도 좋지만 굳이 리뷰를 드리자면
함수명을 getFile __String__ FromBundle에서 getFile __Contents__ FromBundle
그 함수 안에있는 변수명을 __str__ 에서 __fileContents__ 로 바꾸는 건 어떨까요?

2020-05-04 13:11 UTC, 365kim commented on OneDayOneAnswer/OneDayOneAnswer/Utils/FileUtils.swift
> +    guard let str: String = try? String.init(contentsOf: fileURL) else {
변수명 수정제안

2020-05-04 14:22 UTC, 365kim commented on OneDayOneAnswer/OneDayOneAnswer/Utils/FileUtils.swift
> +}
함수명/변수명 수정제안

2020-05-05 05:46 UTC, nadarm commented on OneDayOneAnswer/OneDayOneAnswer/Utils/FileUtils.swift
> +}
좋은 의견 감사합니다

2020-05-05 06:27 UTC, 365kim commented
우선은 피커로만 만들기로 해서 리뷰하지 않고 PR 살려두겠습니다~~

2020-05-05 08:12 UTC, 365kim approved these changes
머지? 머지!

2020-05-05 08:23 UTC, merged